### ISSUE TITLE
Last commit breaks company-posframe in Emacs 27.

### ISSUE THREAD

**Issue by yanghaoxie** [tumashu/company-posframe#14]
After commit 977b7390cc4033ad087c46e7ba9f6fd7a6018869, `company-posframe` buffer blinks, I present an example as follow `gif` picture.

![company-posframe](https://user-images.githubusercontent.com/10540480/60027648-6bf39400-96d0-11e9-836d-0528a546fb2d.gif)

**Comment by aaronjensen** [comment]
Last time this broke, this is what fixed it: https://github.com/tumashu/company-posframe/pull/10/files

**Comment by aaronjensen** [comment]
```elisp
(defun company-posframe-window-change ()
  "Hide posframe on window change."
  (unless (or (string= (buffer-name) company-posframe-buffer)
              (equal company-posframe--last-status
                     (list (selected-window)
                           (current-buffer))))
    (company-posframe-hide)))
```

Fixes it for me

**Comment by yanghaoxie** [comment]
It worked. Thanks, bro. @aaronjensen
