### ISSUE TITLE
Performance problems

### ISSUE THREAD

**Issue by dgutov** [tumashu/company-posframe#17]
It's noticeably slow than the built-in overlay based popup. Even if I disable extra stuff such as "indicator" and "metadata". Try pressing `M-n` and seeing how fact the list is scrolled. The built-in popup scrolling is smooth, posframe-based one is not.

It also affects simply typing since the posframe is updated synchronously anyway.

I'm using Ubuntu 19.04 and GNOME 3.32.1 (for now).

**Comment by tumashu** [comment]
it is true that posframe is slow than popup,  but it should not affect type.

**Comment by dgutov** [comment]
Can we make it into a bug report for Emacs? Like, is there a particular operation on child frames that you found to be inevitably slow?

**Comment by tumashu** [comment]
Today< I have tested company-posframe in gnome, and find that is is much slower than in xfce4. the reason is not be found at the moment.

**Comment by Alexander-Miller** [comment]
[Does this help?](https://github.com/emacs-helm/helm/wiki/FAQ#slow-frame-and-window-popup-in-emacs-26)

**Comment by dgutov** [comment]
I'm using Emacs 27 (latest build) :frowning_face:

**Comment by tumashu** [comment]
i think it is set-frame-size's problem in gnome-shell

**Comment by dgutov** [comment]
> set-frame-size

So it's both slow and doesn't work properly either (#2)?

**Comment by tumashu** [comment]
yes

**Comment by failable** [comment]
Scrolling is slow and laggy on my emacs 26.3 and OSX 10.15.2.

**Comment by tumashu** [comment]
I have send a mail to emacs-devel:  https://lists.gnu.org/archive/html/emacs-devel/2020-01/msg00343.html

**Comment by dgutov** [comment]
With resizing problems taken care of, scrolling is still slow, compared to the overlay-based frontend. You can easily observe this by flooring `M-n`.

I wonder if we could work on improving it next.
