### ISSUE TITLE
Does not work with `company-filter-candidates` and `company-search-candidates`.

### ISSUE THREAD

**Issue by failable** [tumashu/company-posframe#21]
When completion is activated and then `company-filter-candidates` or `company-search-candidates` is invoked, filtering is not performed while the frame sometimes disappear and sometimes sticks there.

**Comment by tumashu** [comment]
Should fixed, please try again https://github.com/tumashu/company-posframe/commit/c1ba65596ee2ea46f0da51861f6cbdbe788625ee

**Comment by failable** [comment]
Thanks for the quick fix. The issue seems gone.
