### ISSUE TITLE
Misbehaves near the bottom of the frame

### ISSUE THREAD

**Issue by dgutov** [tumashu/company-posframe#24]
Open `*scratch*`, make it the sole window in the frame (`C-x 1`).

Add some newlines until the point is at the last visible line.

For this illustration, the buffer should be in `lisp-interaction-mode` or `emacs-lisp-mode`.

Scenario 1:

Type `(def-`, see two completions in the list.

Type `in`, see the list of completions become longer (because of partial completion), and the popup first move on top of the current line, and then, kind of sluggishly, righting itself.

Scenario 2:

Type `(def-inline`. Then slowly start backspacing.

The popup, similarly, will move unexpectedly several times, covering the current line.

**Comment by tumashu** [comment]
Is is possible show some snapshot?

**Comment by dgutov** [comment]
![Screenshot from 2020-01-21 04-04-37](https://user-images.githubusercontent.com/271877/72766984-58c38b00-3c03-11ea-9ffd-1e43ed37c174.png)
![Screenshot from 2020-01-21 04-04-42](https://user-images.githubusercontent.com/271877/72766989-5c571200-3c03-11ea-9bf9-3dad787536c9.png)

**Comment by tumashu** [comment]
![图片](https://user-images.githubusercontent.com/67725/72768357-1d8c8080-3c32-11ea-937a-24035c8b6c4c.png)
xfce4 + emacs27 gtk3, seem to no this problem.

**Comment by dgutov** [comment]
You have to follow the steps I described.

Type `(def-`, stop, then `i`.

**Comment by dgutov** [comment]
Looks like this has been fixed in the meantime. Or at least, I can't repro anymore. Thanks.
