### ISSUE TITLE
tabs in Emacs 27+ affect position of childframe

### ISSUE THREAD

**Issue by andreyorst** [tumashu/company-posframe#37]
withoug `global-tab-line-mode`:
![image](https://user-images.githubusercontent.com/19470159/76678958-5ec75e00-65ed-11ea-9726-0a4aeaa8e6ca.png)

with `global-tab-line-mode`:
![image](https://user-images.githubusercontent.com/19470159/76678979-7ef71d00-65ed-11ea-8831-9849bd29fc79.png)

though this may be posframe issue, not company posframe that depends on it

**Comment by andreyorst** [comment]
It seems that there's no way to set up position function for company posframe, the way it is possible for `ivy-posframe`. I've managed to fix this problem for `ivy-posframe` with thsi simple code:

```emacs-lisp
(defun aorst/posframe-unser-tabs-center (info)
  "Function that sets center position for ivy posframe."
  (cons (/ (- (plist-get info :parent-frame-width)
              (plist-get info :posframe-width))
           2)
        (+ (if global-tab-line-mode (window-tab-line-height) 0))))
```

It seems to fix this issue the only needed code is

```emacs-lisp
:y-pixel-offset (if (bound-and-true-p global-tab-line-mode) (window-tab-line-height) 0)
```

in `company-posframe-show` function. Again, I don't know if this should be fixed in posframe itself

**Comment by tumashu** [comment]
this should be fixed in posframe

**Comment by tumashu** [comment]
https://github.com/tumashu/posframe/commit/8db93024c32ee3b12805952d3d9ba524a42e79ca

**Comment by andreyorst** [comment]
Yes, seems it fixed company-posframe. Huge thanks!
