### ISSUE TITLE
company-posframe-quickhelp wrong position in some cases

### ISSUE THREAD

**Issue by zsxh** [tumashu/company-posframe#40]
![Peek 2020-05-02 14-54](https://user-images.githubusercontent.com/10348978/80857622-155acd00-8c86-11ea-8b62-5416e88d3aff.gif)

在右边缘部分，company-posframe tooltip 部分会被 quickhelp 挡住

**Comment by tumashu** [comment]
我感觉这是正常反应。。。

在 2020-05-02 15:25:49，zsxh <notifications@github.com> 写道：


在右边缘部分，company-posframe tooltip 部分会被 quickhelp 挡住

**Comment by zsxh** [comment]
主要是在输入过程中补全列表也是被挡住的，当我在右边buffer里敲代码时，补全列表基本处于不可见的状态。不知道有没有办法将quickhelp的窗口永远置于补全窗口之后，像company-box那样即使显示不全也没关系 :thinking:

**Comment by tumashu** [comment]
有可能

**Comment by tumashu** [comment]
今天试了一下设置z-group, 但是没有成功，不知道是姿势不对，还是踩到坑了

**Comment by tumashu** [comment]
应该修复了，试试吧

**Comment by zsxh** [comment]
非常好使，感谢大佬
