### ISSUE TITLE
Empty candidates list

### ISSUE THREAD

**Issue by muffinmad** [tumashu/company-posframe#5]
Steps to reproduce:
1. `emacs -Q`, enable company-mode and company-posframe-mode
2. Write something that will show candidates list:
![candidates](https://i.imgur.com/Nz9kplj.png)
3. Type character that not match completions:
![empty candidates](https://i.imgur.com/HPiCkag.png)

**Comment by galeo** [comment]
It should check whether the candidates list is empty before calling `posframe-show` to display the candidate menu. When `:string` attribute is `nil`, `posframe-show` still displays a single character size of childframe that shows in the second screenshot of above (in the beginning of second line).

**Comment by galeo** [comment]
By observing the commands that company triggers in a completion process, this issue can be solved by just set `show` argument undefined in `company-posframe-frontend`. Here is the log message I set in debug:

```
> command: ’show’ show-inline-p: ’nil’
> command: ’update’ show-inline-p: ’nil’
> command: ’post-command’ show-inline-p: ’nil’
> command: ’pre-command’ show-inline-p: ’nil’
> command: ’post-command’ show-inline-p: ’nil’
> command: ’pre-command’ show-inline-p: ’nil’
> command: ’hide’ show-inline-p: ’nil’
> command: ’show’ show-inline-p: ’nil’
``` 

Company will trigger an extra `show` command after `hide` command when typing a character that not match completions. This behavior should be avoided.
