### ISSUE TITLE
company--create-lines return value changed

### ISSUE THREAD

**Issue by dgutov** [tumashu/company-posframe#52]
Hi!

Please be aware that I've just changed the return value of this function to `(COLUMN-OFFSET . LINES)` in company-mode master.

Should be easy to detect this version: just check whether the car of the list is a number, and if so, use its cdr.

**Comment by dgutov** [comment]
@tumashu Thank you, that seems to work.

Another thing you might want to change (which will require a less trivial rearrangement), if positioning of the tooltip when icons are shown: it is now off by 1 column.

The `COLUMN-OFFSET` value contains the necessary offset, to be used in `company-posframe-show-at-prefix` instead of `company-tooltip-margin`, but I'm not sure how to get it there best.

**Comment by tumashu** [comment]
@dgutov how to enable icon in margin?

**Comment by dgutov** [comment]
@tumashu 

* Have Emacs compiled with SVG support.
* Update to the latest company from MELPA.
* `(setq company-format-margin-function #'company-vscode-light-icons-margin)`
* Use a backend that provides support, such as `company-dabbrev-code`, `company-yasnippet`, `lsp-mode` or (if you build Emacs from master) `emacs-lisp-mode`.

**Comment by tumashu** [comment]
Should be fixed. https://github.com/tumashu/company-posframe/commit/26d15ab77f61a089299d739c83ba648cdc36ca0d

**Comment by dgutov** [comment]
Working well, thank you.

I though it would be easy to pass the extra offset lexically through some arg (`:position`, perhaps), but it seems that would run counter to the reason `company-posframe-poshandler` was introduced.

**Comment by tumashu** [comment]
maybe we can introduce  :poshandler-extra-info to posframe-show,  with this argument help, we can pass any info to poshandler function.

**Comment by dgutov** [comment]
That should work, yes. Maybe pass an alist with 3 values: current pos, company-prefix length, and margin offset. The handler should be able to decide based on them.

Nothing urgent, though, so whenever you have the time to experiment.

**Comment by tumashu** [comment]
@dgutov  fixed. https://github.com/tumashu/company-posframe/commit/a28f38213a2a30ce68fdb0b124cadc68ebbcb24f

**Comment by dgutov** [comment]
@tumashu Looking good, thanks!
