### ISSUE TITLE
Support company-tng-mode

### ISSUE THREAD

**Issue by ctrl2wei** [tumashu/company-posframe#54]
If enable company-tng-mode, company will not select any candidate at begin. and Emacs will show error:
```
Error running timer ‘company-posframe-quickhelp-show’: (wrong-type-argument numberp nil) 
```

**Comment by tumashu** [comment]
When I enable this mode, seem to no this problem, try emacs -Q to test.

**Comment by ctrl2wei** [comment]
错误出在 424 行的代码，
https://github.com/tumashu/company-posframe/blob/a28f38213a2a30ce68fdb0b124cadc68ebbcb24f/company-posframe.el#L421-L427
company-tng-mode 默认开始没有选中任何 candidate，company-selection 值为 nil。

**Comment by tumashu** [comment]
please try again.

**Comment by ctrl2wei** [comment]
运行良好，感谢！
