### ISSUE TITLE
posframe blink when working with lsp-mode in emac-mac-port

### ISSUE THREAD

**Issue by P233** [tumashu/company-posframe#56]
I record a screencast for this issue. The posframe blinks frequently when candidates come from lsp-mode, but in other major modes it doesn't bink at all.

This is happened on the latest emacs mac port (arm64 version), I am not sure if it is also happened in other emacs versions. If you need any other information, please let me know.

Thanks for the hard working of posframe!

https://user-images.githubusercontent.com/1818679/145678527-058ae561-773b-4880-a68d-43e8f42a244c.mov

**Comment by tumashu** [comment]
I think i hard to understand why.

**Comment by tumashu** [comment]
I think i hard to understand why.

**Comment by P233** [comment]
Thanks for the quick reply.

Not a big deal. I am now using numbers shortcut instead of `up` or `down` keys, that won't cause posframe blink.

I post this issue because I thought you might have some ideas. But if you think this is a randam case, or maybe not compatible with some specific version of emacs mac port. I'll close this issue.

**Comment by P233** [comment]
I switch to TabNine completion instead of the lsp completion this moning, the blink issue just gone. Probably caused by the lsp mode.

**Comment by Yevgnen** [comment]
I don't use LSP but I get the same issue when using `company-capf` in an emacs-lisp buffer on a Mac.

**Comment by tumashu** [comment]
@Yevgnen I have updated posframe to solve flicker in windows, can you try the master posframe code in macos?  maybe useful in macos too :-)

**Comment by Yevgnen** [comment]
@tumashu Hi, unfortunately the current version e104c0d0ee8db4a5fc852b3fc951e52989ee8755 does not seem  work on my macOS 12.1 and `GNU Emacs 27.2 (build 1, x86_64-apple-darwin21.1.0, Carbon Version 165 AppKit 2113) of 2021-11-01`. Every two or three <kbd>C-p</kbd> or <kbd>C-n</kbd> cause the flickers.

**Comment by tumashu** [comment]
pkease update posframe and try again

**Comment by P233** [comment]
The last commit works for me.
