### ISSUE TITLE
company-posframe breaks company-pseudo-tooltip-frontend

### ISSUE THREAD

**Issue by wbthomason** [tumashu/company-posframe#7]
As diagnosed in https://github.com/company-mode/company-mode/issues/854, using `company-posframe-frontend` in GUI Emacs precludes using `company-pseudo-tooltip-frontend` in terminal Emacs. I believe the offending line is: https://github.com/tumashu/company-posframe/blob/master/company-posframe.el#L152

What would be the best way to fix or work around this? Perhaps a function to undo the advices?

**Comment by tumashu** [comment]
Fixed, please try again

**Comment by wbthomason** [comment]
Thanks, that fixed my issue!
