### ISSUE TITLE
Conflict with display-line-numbers ?

### ISSUE THREAD

**Issue by ghost** [tumashu/company-posframe#8]
I use evil-mode so have this config below to obtain a relative line number:
```elisp
(setq-default display-line-numbers 'relative
				 display-line-numbers-widen t
				 display-line-numbers-current-absolute t) 

  (defun noct:relative ()
	(setq-local display-line-numbers 'relative))
  (defun noct:absolute ()
	(setq-local display-line-numbers t))

  (add-hook 'evil-insert-state-entry-hook #'noct:absolute)
  (add-hook 'evil-insert-state-exit-hook #'noct:relative)
```

That gives posframe a relative line number too, but i want disable that, because it will cut off a part of the content , like this:
![gegeg](https://user-images.githubusercontent.com/37837882/50808191-62e85380-1338-11e9-9162-c7ae71a58ed7.PNG)

I tried:
```elisp
(add-hook 'company-posframe-mode-hook
	  (lambda () (display-line-numbers-mode -1)))
```
but it dosent work.

**Comment by tumashu** [comment]
Fixed in posframe: https://github.com/tumashu/posframe/commit/d141d56d1c747bca51f71f04fdb9d4d463996401

**Comment by ghost** [comment]
The commite fix that, thanks!!
